# Generated by Django 5.0.2 on 2024-03-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=32)),
                ('logo', models.CharField(max_length=128)),
                ('market_cap', models.IntegerField()),
                ('price', models.FloatField()),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=32)),
                ('market_cap', models.IntegerField()),
                ('sector', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('dividend', models.FloatField()),
                ('volume', models.IntegerField()),
                ('country', models.CharField(max_length=3)),
                ('exchange', models.CharField(max_length=16)),
                ('is_etf', models.BooleanField(default=False)),
            ],
        ),
    ]
