# Generated by Django 5.0.2 on 2024-03-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
