# Generated by Django 5.0.2 on 2024-03-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_alter_stock_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='country',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
