# Generated by Django 5.0.2 on 2024-03-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0004_alter_stock_dividend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'ordering': ['-market_cap']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-market_cap']},
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='market_cap',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='volume',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.BigIntegerField(),
        ),
    ]
