# Generated by Django 5.0.2 on 2024-03-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolio_crypto_remove_portfolio_stocks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='crypto',
            field=models.ManyToManyField(blank=True, to='portfolio.cryptoportfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='stocks',
            field=models.ManyToManyField(blank=True, to='portfolio.stockportfolio'),
        ),
    ]
