# Generated by Django 5.0.2 on 2024-03-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_crypto_alter_portfolio_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockportfolio',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
