# Generated by Django 5.0.2 on 2024-04-02 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoportfolio',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='crypto_portfolio_owner', to='portfolio.portfolio'),
        ),
    ]
