# Generated by Django 5.0.2 on 2024-04-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_cryptoportfolio_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoportfolio',
            name='shares',
            field=models.FloatField(default=0),
        ),
    ]
