# Generated by Django 5.0.2 on 2024-04-13 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_cryptoportfolio_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='transactions',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_transactions', to='portfolio.transaction'),
            preserve_default=False,
        ),
    ]
