# Generated by Django 5.0.2 on 2024-04-13 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_portfolio_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='transactions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_transactions', to='portfolio.transaction'),
        ),
    ]
