# Generated by Django 5.0.2 on 2024-04-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_portfolio_transactions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='transactions',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='transactions',
            field=models.ManyToManyField(blank=True, null=True, related_name='portfolio_transactions', to='portfolio.transaction'),
        ),
    ]
