# Generated by Django 5.0.2 on 2024-04-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='portfolio_transactions', to='portfolio.transaction'),
        ),
    ]
